### PR TITLE
Refactor time domain PLAsTiCC photometry class

### PR DESCRIPTION
**Pull request by utthishtastro**
The PR contains refactoring of `PLAsTiCCPhotometry` class `(time_domain_PLAsTiCC.py)` and it depends on #52 

`PLAsTiCCPhotometry` and `SNPCCPhotometry` classes share similar methods. In the future we can have a main class with common methods and inherit `PLAsTiCCPhotometry` and `SNPCCPhotometry` from it.

### CODE REVIEW

**Comment by emilleishida** [comment]
hi @utthishtastro sorry for the late reply on this, 
I am getting this error when trying to fit the `object_id = 13` from the first file of `plasticc_test_lightcurves_01.csv.gz`.
I get the feeling this is related to the progress bar.

can you confirm if this happens to you or not?

[330 rows x 5 columns]
Traceback (most recent call last):
  File "fit_PLAsTiCC_pool_time_domain.py", line 48, in <module>
    tel_names=['4m', '8m'], feature_method='Bazin', spec_SNR=10)
  File "/media/emille/git/COIN/RESSPECT_repo/rupesh/rupesh-env/lib/python3.7/site-packages/resspect-0.1-py3.7.egg/resspect/time_domain_PLAsTiCC.py", line 465, in fit_one_lc
TypeError: 'module' object is not callable

**Comment by emilleishida** [comment]
sorry I found out what this is. 
It is neessary to install progressbar2 as well, and then it works. 

I am closing this issue and will add progressbar2 to the requirements. 
sorry for the noise

**Comment by utthishtastro** [comment]
Hi @emilleishida, only progressbar2 is sufficient. It is already available in [requirements.txt](https://github.com/COINtoolbox/RESSPECT/blob/master/requirements.txt#L15) file. Cheers!

**Comment by emilleishida** [comment]
hi @utthishtastro one more thing, 

when I do:

`database = PLAsTiCCPhotometry()`
`database.create_all_daily_files(.....)`
`database.read_metadata(....)`
`database.fit_one_lc( ... )`

when I create the daily files they are created with header, but once I use the `fit_one_lc` function the header disappears.

**Comment by utthishtastro** [comment]
@emilleishida Updated. But please check if the header with cost is proper in [master branch](https://github.com/COINtoolbox/RESSPECT/blob/master/resspect/time_domain_PLAsTiCC.py#L110).  I think `uA uB ut0 utfall utrise YA YB Yt0 Ytfall Ytrise` are missing. Please let me know if that is the case, I will update the PR with the correct header for cost

**Comment by emilleishida** [comment]
hi @utthishtastro you are correct. 
`uA uB ut0 utfall utrise YA YB Yt0 Ytfall Ytrise` are missing.

also, in the header without cost there is a space missing:
`ztriseYA`   should be `ztrise YA`

**Comment by utthishtastro** [comment]
@emilleishida thanks, updated accordingly.

**Comment by emilleishida** [comment]
Last thing, the fit works for DDF and for WFD if I give the number of the file, but if I use `vol = None`   it does not seem to find it

`Traceback (most recent call last):
  File "/media/emille/git/COIN/RESSPECT_repo/rupesh/rupesh-env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'mjd'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "fit_PLAsTiCC_pool_time_domain.py", line 49, in <module>
    tel_names=['4m', '8m'], feature_method='Bazin', spec_SNR=10)
  File "/media/emille/git/COIN/RESSPECT_repo/rupesh/rupesh-env/lib/python3.7/site-packages/resspect-0.1-py3.7.egg/resspect/time_domain_PLAsTiCC.py", line 464, in fit_one_lc
  File "/media/emille/git/COIN/RESSPECT_repo/rupesh/rupesh-env/lib/python3.7/site-packages/resspect-0.1-py3.7.egg/resspect/time_domain_PLAsTiCC.py", line 234, in _get_fit_days
  File "/media/emille/git/COIN/RESSPECT_repo/rupesh/rupesh-env/lib/python3.7/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/media/emille/git/COIN/RESSPECT_repo/rupesh/rupesh-env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'mjd'
`

**Comment by utthishtastro** [comment]
@emilleishida updated. Please check now.

**Comment by emilleishida** [comment]
Now I get the following error ... it still seems to be related to the progress bar.

`N/A% (0 of 1) |                                                                                        | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "fit_PLAsTiCC_pool_time_domain.py", line 48, in <module>
    tel_names=['4m', '8m'], feature_method='Bazin', spec_SNR=10)
  File "/media/emille/git/COIN/RESSPECT_repo/rupesh/rupesh-env/lib/python3.7/site-packages/resspect-0.1-py3.7.egg/resspect/time_domain_PLAsTiCC.py", line 476, in fit_one_lc
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
`

**Comment by emilleishida** [comment]
Some other small issues:

Please remove print from line 172

https://github.com/utthishtastro/RESSPECT/blob/45eeea2cdaa36aa41e7ab875068aa0761e5dbc91/resspect/time_domain_PLAsTiCC.py#L172


and the function `_update_light_curve_meta_data` needs docstring.

**Comment by emilleishida** [comment]
hi @utthishtastro I found the problem, 
the only issue was that the PLAsTiCC zenodo files start from 1, not 0. 

so I just made the starting point of the counter here
https://github.com/utthishtastro/RESSPECT/blob/45eeea2cdaa36aa41e7ab875068aa0761e5dbc91/resspect/time_domain_PLAsTiCC.py#L211

to be 1.

I am accepting this and will make the small change in the main branch. 
Thank you deeply for the help on this!

**Pull request merged**
