### PR TITLE
[In Progress] Modify LightCurve class to allow creation of feature extractor classes

### PR DESCRIPTION
**Pull request by utthishtastro**
New feature extractor classes can be added using `LightCurve` base class 
Feature extractor class should implement necessary methods. Please check `BazinFeatureExtractor` or `BumpFeatureExtractor` for reference
```
class NewFeatureExtractor(LightCurve):
    def __init__(self):
        super().__init__()

    def evaluate(self):
        """
        Evaluate the Bazin function given parameter values.
        """

    def fit(self):
        """
        Extracts features for one filter.
        """

    def fit_all(self):
        """
        Performs fit for all filters independently and concatenate results.
        """

    def plot_fit(self):
        """
        Plots data with fitted function.
        """
```
Todo:
- [ ] Bump extractor headers are missing
- [ ] Verify the implementation with different datasets

### CODE REVIEW

**Comment by emilleishida** [comment]
I think I more or less understood what is the idea, of separating the LightCurve object from the fitting part, which it seems a good thing to me. 

Just a few points:

- having files with the same name in different folders is confusing. There are `resspect/bazin.py` and `resspect/feature_extractors/bazin.py`  I would name them slightly different

- I tried to load the `BazinFeatureExtractor` but I got

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_452408/3030310545.py in <module>
      1 lc1 = LightCurve()
----> 2 bfe_test = bfe(lc1)

TypeError: __init__() takes 1 positional argument but 2 were given


----------------------------------------------------------------------------

I understood that a `LightCurve` object should be given, but maybe I got that wrong

**Comment by utthishtastro** [comment]
@emilleishida 
1. I'll rename the files 👍 

2. Bazin and Bump feature extractor classes have been defined can be accessed as below
``` python
# bazin
bazin_lc = BazinFeatureExtractor()
bazin_lc.load_snpcc_lc(path_to_feature_file)

# bump
bump_lc = BumpFeatureExtractor()
bump_lc.load_snpcc_lc(path_to_feature_file)
```

A new feature extractor class can be added as described in the first comment. Let me know if you have further questions

**Comment by emilleishida** [comment]
@utthishtastro this is great, thanks!
apologies for taking so long, but I looked at this and it seems to be working fine!
I also tried with plasticc data and it is ok. Do not worry about RESSPECT light curves, that will probably be removed. 

when I tried to plot the bump light curve I got an error

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_227509/1149545446.py in <module>
----> 1 bump_lc.plot_fit()

/media/emille/git/COIN/RESSPECT_repo/rupesh/rupesh-env/lib/python3.7/site-packages/resspect-0.1-py3.7.egg/resspect/feature_extractors/bump.py in plot_fit(self, save, show, output_file, figscale, extrapolate, time_flux_pred, unit)
    155             if plot_fit:
    156                 xaxis = np.linspace(min(time), max(time), 500)[:, np.newaxis]
--> 157                 fitted_flux = np.array(self.evaluate(xaxis)[self.filters[i]]) * self.features[i * 5 + 4]
    158                 if unit == 'flux':
    159                     plt.plot(xaxis, fitted_flux, color='red',

/media/emille/git/COIN/RESSPECT_repo/rupesh/rupesh-env/lib/python3.7/site-packages/resspect-0.1-py3.7.egg/resspect/feature_extractors/bump.py in evaluate(self, time)
     42                         bump(item, self.features[0 + k * 5],
     43                              self.features[1 + k * 5],
---> 44                              self.features[2 + k * 5]))
     45             else:
     46                 flux[self.filters[k]].append(None)

TypeError: 'module' object is not callable`

**Comment by emilleishida** [comment]
I do need this, so I will merge now and we fix the plot issue latter
I will comment the plot function -- I know this is not correct, but it is necessary

**Comment by emilleishida** [comment]
so coming back to this, the error can be reproduced by:

-------
`from resspect.feature_extractors.bump import BumpFeatureExtractor

path_to_feature_file = '/media/RESSPECT/data/SNPCC/raw/SIMGEN_PUBLIC_DES/DES_SN729076.DAT'


bump_lc = BumpFeatureExtractor()
bump_lc.load_snpcc_lc(path_to_feature_file)
bump_lc.fit_all()
bump_lc.plot_fit()`

**Pull request merged**
